[package]
name = "linkchecker"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
regex = "1"
reqwest = "0.13"
tempfile = "3.24"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
httpmock = "0.7"
